name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      

      - run: pod repo update
        working-directory: MatchMakeriOS

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: MatchMakeriOS

      - run: mv Runner.app/ Payload
        working-directory: MatchMakeriOS

      - name: Zip output
        run: zip -qq -r -9 IpaExport.ipa Payload
        working-directory: MatchMakeriOS

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MatchMakeriOS/IpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
