name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name:  iOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: pod install --repo-update
        working-directory: MatchMakeriOS

      - name: Set up Xcode
        run: xcodebuild -workspace MatchMaker.xcworkspace -scheme MatchMaker -configuration Release -sdk iphoneos -derivedDataPath build

      - name: Build IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath build/Build/Products/MatchMaker.xcarchive \
          -exportPath build/Build/Products \
          -exportOptionsPlist MatchMakeriOS/ExportOptions.plist
        working-directory: MatchMakeriOS

      - name: Rename IPA
        run: mv build/Build/Products/MatchMaker.ipa build/Build/Products/MatchMakerExport.ipa
        working-directory: MatchMakeriOS

      - name: Upload IPA to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MatchMakeriOS/build/Build/Products/MatchMakerExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
